const fs=require("fs")
const path=require("path")
const os = require("os")


const TEMPLATE=path.join(__dirname,"../src/dos/dosbox/ts/worker-server.js")
const NODEJS_SHIM=path.join(__dirname,"../worker-shim.js")

const config={
    dosbox:"dosbox.js"
}

function append(file,MODULE_NAME){
    const filePath=path.join(__dirname,"../",file)
    let fileContent=fs.readFileSync(filePath,"utf-8")
    const header="// This file is generated by .github/wasmjs.js, do not edit it manually";
    if (fileContent.includes(header)){
        fileContent=fileContent.split(header)[0]
    }

    const templateContent=fs.readFileSync(TEMPLATE,"utf-8")
    const newContent=templateContent.replace(/@MODULE_NAME@/g,MODULE_NAME)
    const shimContent=fs.readFileSync(NODEJS_SHIM,"utf-8")
    const newFileContent=`
${fileContent}

${header}
${shimContent}
${newContent}`;
    fs.writeFileSync(filePath,newFileContent,"utf-8")
    console.log(`File ${filePath} updated successfully!`);
}

append("build/wasm/wdosbox.js","WDOSBOX")
append("build/wasm/wdosbox-x.js","WDOSBOXX")