
/* eslint-disable */
// Autogenerated
// -------------
// gulpfile.ts/wasm.ts --> generateBuildInfo

export const Build = {
    version: "8.3.3-dosasm9 (47cd8761f3f98c54379a24e426b78066)",
    buildSeed: 1739885455749,
    "wdosbox-x.wasm": {
        "size": 6294385,
        "gzSize": 2292969
    },
    "wdosbox-x.js": {
        "size": 225479,
        "gzSize": 53225
    },
    "wdosbox.wasm": {
        "size": 1479916,
        "gzSize": 504496
    },
    "wdosbox.js": {
        "size": 103037,
        "gzSize": 27449
    },
    "wlibzip.wasm": {
        "size": 112716,
        "gzSize": 52237
    },
    "wlibzip.js": {
        "size": 74570,
        "gzSize": 19814
    }
,
};
