
/* eslint-disable */
// Autogenerated
// -------------
// gulpfile.ts/wasm.ts --> generateBuildInfo

export const Build = {
    version: "8.4.0-dosasm0.3 (63130cad44ae9b2dcb73f7a5699faa1a)",
    buildSeed: 1782436817574,
    "wdosbox-nodefs.wasm": {
        "size": 1459779,
        "gzSize": 0
    },
    "wdosbox-nodefs.js": {
        "size": 117551,
        "gzSize": 0
    },
    "wdosbox-x-jspi.wasm": {
        "size": 7716030,
        "gzSize": 0
    },
    "wdosbox-x-jspi.js": {
        "size": 230214,
        "gzSize": 0
    },
    "wdosbox-x-nodefs.wasm": {
        "size": 7858987,
        "gzSize": 0
    },
    "wdosbox-x-nodefs.js": {
        "size": 236303,
        "gzSize": 0
    },
    "wdosbox-x.wasm": {
        "size": 7858987,
        "gzSize": 0
    },
    "wdosbox-x.js": {
        "size": 229414,
        "gzSize": 0
    },
    "wdosbox.wasm": {
        "size": 1459779,
        "gzSize": 0
    },
    "wdosbox.js": {
        "size": 110662,
        "gzSize": 0
    },
    "wlibzip.wasm": {
        "size": 112479,
        "gzSize": 0
    },
    "wlibzip.js": {
        "size": 72957,
        "gzSize": 0
    }
,
};
