
/* eslint-disable */
// Autogenerated
// -------------
// gulpfile.ts/wasm.ts --> generateBuildInfo

export const Build = {
    version: "8.3.3-dosasm3 (a0aa412d00b107b09cb42977e823b64a)",
    buildSeed: 1735270484798,
    "wdosbox-x.wasm": {
        "size": 6307498,
        "gzSize": 2296656
    },
    "wdosbox-x.js": {
        "size": 231324,
        "gzSize": 54889
    },
    "wdosbox.wasm": {
        "size": 1482970,
        "gzSize": 505099
    },
    "wdosbox.js": {
        "size": 109077,
        "gzSize": 29286
    },
    "wlibzip.wasm": {
        "size": 112408,
        "gzSize": 52240
    },
    "wlibzip.js": {
        "size": 74095,
        "gzSize": 19630
    }
,
};
