name: build

on:
  push:
    branches: [ 8.xx ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ 8.xx ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        emsdk-version: [3.1.68]
        binaryen-version: [version_119_e]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: build emulators
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'
    - run: sudo apt-get -yqq update
    - run: sudo apt-get install -yq --no-install-recommends cmake ninja-build zip
    - run: npm install -g yarn
    - run: yarn
    - run: yarn run eslint src --ext ts,tsx --max-warnings 0
    - run: yarn run eslint test --ext ts,tsx --max-warnings 0
    - run: yarn run tsc --noemit
    - run: cd native/sockdrive/js && yarn && yarn run webpack && cd ../../..
    - run: git clone https://github.com/emscripten-core/emsdk.git
    - run: cd emsdk && ./emsdk install ${{ matrix.emsdk-version }} && ./emsdk activate ${{ matrix.emsdk-version }} && cd ..
    - run: wget https://github.com/caiiiycuk/binaryen-fwasm-exceptions/releases/download/${{ matrix.binaryen-version }}/binaryen-${{ matrix.binaryen-version }}-x86_64-linux.tar.gz
    - run: tar xfv binaryen-${{ matrix.binaryen-version }}-x86_64-linux.tar.gz
    - run: cp -v binaryen-${{ matrix.binaryen-version }}/bin/wasm-opt ./emsdk/upstream/bin/wasm-opt
    - run: source ./emsdk/emsdk_env.sh && yarn run gulp production
    - run: zip -9r release.zip dist/*
    - name: build dosplay
      run: cd dosplay && yarn && yarn run build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      # If you're changing the branch from main,
      # also change the `main` in `refs/heads/main`
      # below accordingly.
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dosplay/dist
